site_name: System-100X Technical Wiki
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
nav:
  - Home: index.md
  - Modules:
      - 112-182 Modules: modules/standard.md
      - 182-E Entropy: modules/entropy.md
      - Temanforce: modules/temanforce.md
  - Philosophy:
      - Sound Entropy: architecture/entropy.md
      - Non-Linear Math: architecture/dsp.md
